export enum ScreenName {
	BottomTab = 'BottomTab',
	Home = 'Home',
	Calendar = 'Calendar',
	AllTodo = 'AllTodo',
	Login = 'Login',
	Join = 'Join',
	CreateDiary = 'CreateDiary',
	Diary = 'Diary',
	AddTodo = 'AddTodo',
	AlertSetting = 'AlertSetting',
	CustomerService = 'CustomerService',
	Information = 'Information',
	Mypage = 'Mypage',
	Notice = 'Notice',
	PatManagement = 'PatManagement',
	Profile = 'Profile',
	Profiles = 'Profiles',
	CreateProfile = 'CreateProfile',
	VersionInformation = 'VersionInformation',
	PetType = 'PetType',
	BreedType = 'BreedType',
	AddPet = 'AddPet',
}