export enum ScreenName {
	BottomTab = 'BottomTab',
	Home = 'Home',
	Calendar = 'Calendar',
	AllTodo = 'AllTodo',
	Login = 'Login',
	Join = 'Join',
	CreateRecord = 'CreateRecord',
	Record = 'Record',
	AddTodo = 'AddTodo',
	AlertSetting = 'AlertSetting',
	CustomerService = 'CustomerService',
	Information = 'Information',
	Mypage = 'Mypage',
	Notice = 'Notice',
	PatManagement = 'PatManagement',
	Profile = 'Profile',
	VersionInformation = 'VersionInformation',
	AddPet = 'AddPet',
}