export enum ScreenName {
	BottomTabNavigator = 'BottomTabNavigator',
	Home = 'Home',
	Login = 'Login',
	Join = 'Join',
	CreateRecord = 'CreateRecord',
	AddTodo = 'AddTodo',
	AlertSetting = 'AlertSetting',
	CustomerService = 'CustomerService',
	Information = 'Information',
	Mypage = 'Mypage',
	Notice = 'Notice',
	PatManagement = 'PatManagement',
	Profile = 'Profile',
	VersionInformation = 'VersionInformation',
}